teknologi-umum/blog

- giscus.json
- package-lock.json
- package.json
- pages/posts/[slug].tsx
closes #18 
reference for checking my work and all:
- giscus website: https://giscus.app/
- giscus react component: https://github.com/giscus/giscus-component/tree/main/packages/react
- giscus advanced usage (for controlling allowed origin urls): https://github.com/laymonage/giscus/blob/main/ADVANCED-USAGE.md
proof that my PR is working:
link to discussion: https://github.com/teknologi-umum/blog/discussions/21
> feat: implement giscus for comment section

- content/belajar-docker-dalam-15-menit.md
- content/belajar-typescript-dalam-30-menit.md
> chore: added 2 blog posts

- components/BackToTop.tsx
- components/Navbar.tsx
- package-lock.json
- package.json
- utils/_modules.ts
installed material icons
added search icons to refer user to search page
> fixed bugs when searching blog posts with tags enabled

- content/beralih-dari-cra-ke-vite.md
- package-lock.json
Membuat blog baru dengan nama file `beralih-dari-cra-ke-vite.md` pada folder `./content`.
Blog tersebut sedikit membahas tentang sebuah Build Tools, yakni Vite. dan membahas perbandingan tools instalasi React antara `create-react-app` dengan Vite cli `npm init vite@latest -- --template react`
> Memubuat blog baru

- next.config.js
- package-lock.json
- package.json
- pages/about.tsx
- tsconfig.json
> fix: about page alignment

- content/separate-routing-in-laravel.md
I will move my thread on my twitter account here. pls accept me :dango:
> add post about laravel by wahidin

- content/membuat-vite-agar-mendukung-browser-lama.md
> new blog post: membuat vite agar mendukung browser lama

- pages/posts/[slug].tsx
#73  solution add prose break-word on ul (affecting ol li tag) and code
> fix: bug #73

- content/membuat-vite-agar-mendukung-browser-lama.md
> new content: testing

- styles/globals.css
add numbering in pre tag so it like this
> feat: add numbering on pre tag

- content/introductory-to-treesitter.md
nulis sambil ngantuk, gatau isinya gimana
> chore(post): add introductory to treesitter

- content/apa-itu-vim-secara-singkat.md
> add new content about definition vim

- content/after-interviewing-software-engineers.md
> feat: add post about interviewing software engineers

- content/storing-in-cloud-must-try.md
Please review, it's been a long time since i write in englesh
> [ADD] make content about storing in cloud storage

- content/belajar-dari-binary-search.md
notes: soal gambar gimana ya, langsung hot link aja gak apa-apa?
> feat: new article about lesson learned from binary search 

- pages/search.tsx
- services/filter-post.ts
closes issue #109 
post terakhir om jason field `desc` nya kosong soalnya
> fix: handle client error from empty markdown field

- pages/search.tsx
> refactor: search tags hover state

- components/BrowseTopic.tsx
make it less cluttered especially on mobile
> feat: toggle more/less topics

- components/ImageWithFrame.tsx
> fix: figcaption overflows

- CONTRIBUTING.md
- pages/about.tsx
Updating Telegram Group link to the new group.
> Update Telegram group link

- components/FeaturedPost.tsx
> fix(FeaturedPost): dark theme color collision

- pages/posts/[slug].tsx
> chore: og image for post

- pages/_app.tsx
Our analytics uses Umami, so it's obviously respect user privacy
> feat: enable analytics

- components/AuthorCard.tsx
- components/Contributing.tsx
- components/Footer.tsx
- components/Navbar.tsx
- pages/about.tsx
See docs https://umami.is/docs/track-events
> feat: add tracking events for outgoing links

- pages/_app.tsx
[fix this issue](https://github.com/teknologi-umum/blog/issues/157)
from this
https://github.com/user-attachments/assets/b2876de2-ee9f-4048-988b-35c7c0696a13
to this
https://github.com/user-attachments/assets/c211b824-70d7-46de-a2f4-95f325476313
> fix: avoid flash of default theme
